### ISSUE TITLE
Unable to completely disable mic usage

### ISSUE THREAD

**Issue by VladWinner** [h1-mod/h1-mod#157]
Game continues to use the microphone and Krisp app reduces available minutes as if voice chat is active.
![image](https://user-images.githubusercontent.com/13555921/177112302-9dc0494d-1396-4453-a540-86aa77794a48.png)
![image](https://user-images.githubusercontent.com/13555921/177234239-d87a0fdc-16d8-46aa-bad0-8bc164f41443.png)
And `cl_voice 0` console command, as well as mic related 5c61e2a commit doesn't affect this.
Since this is a "classic app", Windows 10/11 system settings don't allow to disable the microphone only in this game.

**Comment by mjkzy** [comment]
why do you need to disable mic usage for the game? sure, its unused but does it actually hurt anything

**Comment by VladWinner** [comment]
> Krisp app reduces available minutes as if voice chat is active
I gave a practical example: this forces me to disable the noise reduction app so as not to spend all available daily call minutes. 
Or it may (theoretically) conflict with some apps that check if the microphone is used anywhere else.

**Comment by VladWinner** [comment]
I guess if somehow specify `null` as the input audio device, then this would solve the problem.

**Comment by mjkzy** [comment]
gonna close since the workaround probably works good enough. 

for future reference, possibly patching stuff in `Mixer_InitWaveInLineInfo` may work. this function does windows API stuff with the mixer and that's what determines the input device *i think*. however, it's kinda hard to specify a null mixer ID because I think the game doesn't check if a valid mixer ID is being used...
