### ISSUE TITLE
Bots will only use default classes upon death on Dedicated Servers

### ISSUE THREAD

**Issue by DashupDragonInstall** [h1-mod/h1-mod#240]
I've noticed while playing alone, bots will use custom classes, but once they die, they will revert to using only the default classes
on Dedicated Servers.
However, they will keep their custom classes in private matches.

**Comment by mjkzy** [comment]
is this actually a issue that needs fixed that bad or

**Comment by DashupDragonInstall** [comment]
> is this actually a issue that needs fixed that bad or

Not at all, I was just reporting it since it seemed like unintentional behavior, but really, quite a minor issue since bots are really just there to be cannon fodder until real players join. Thanks for all your work, and I appreciate the reply!

**Comment by mjkzy** [comment]
looking at this, i'm pretty sure this happens because of us or its just genuinely broken?
in our code, we spawn a bot and handle the bot's team joining and selecting a random custom class the bot has

https://github.com/h1-mod/h1-mod/blob/4cbb0257be065e71383b3bcf2817b8ebb5b0a46b/src/client/component/bots.cpp#L34-L39

**Comment by mjkzy** [comment]
closed as this is not important to fix at the moment. if you want to fix, just use GSC and modify the bots classes
