### ISSUE TITLE
h1_dedicated_server_full.torrent

### ISSUE THREAD

**Issue by dark-age** [h1-mod/h1-mod#604]
No seeds?

**Comment by January-0002** [comment]
Unrelated. Pls close.

**Comment by khabib227** [comment]
No seeds guy because H1 mod is completely dead, the developers don't want keep and support it anymore, was just a lost of time to devs and to us. H1 don't deserve even our attention. But has other Call of Duty mods that you can download the full game easily and has good support, try the other mods. H1 is dead, the developers can archive the project soon.

**Comment by skkuull** [comment]
Nobody cares ab ur opinion lil bro

**Comment by mjkzy** [comment]
we care about the project, but we are more focused on the modding rather than the actual client development.

**Comment by khabib227** [comment]
Who can use the "modding" without seeds? How I can do a dedicated server without seeds? Seeds is essential to keep H1 alive.

**Comment by mjkzy** [comment]
i understand that, but we no longer provide the files. if you can get the game files via Steam, then you can run a dedicated server. all the dedicated server consists of is all the same files without imagefiles/soundfiles present which frees up a bunch of storage

**Comment by mjkzy** [comment]
join the discord if you want to talk about this more
