### ISSUE TITLE
Need Seeds

### ISSUE THREAD

**Issue by khabib227** [h1-mod/h1-mod#656]
Please someone seed the "h1_dedicated_server_full" torrent, I have 85% already, I need just 2gb. How you can get servers and players without seeds?

**Comment by Bububalo** [comment]
No. There is a reason why this stuff was removed. Just get the files the intended way

**Comment by diamante0018** [comment]
You don't need seeds. You need to buy the game.

**Comment by khabib227** [comment]
Who posted the torrents? I or you guys? Is very strange your position now, I'm downloading what you posted to me, you teach me how to download on oficial site, who wrote this article? Has some pirate infiltrated in you team? :D 

https://web.archive.org/web/20221027224312/https://docs.h1.gg/install-server

**Comment by Bububalo** [comment]
I've already stated that they were removed for a reason. Also, neither of us who have replied so far posted the torrents or are even a part of the H1-Mod team. When I said to get the files the intended way, I meant buy the game on Steam since all other forms of getting the game files are no longer supported

**Comment by khabib227** [comment]
I can still wanting for some unsupported seed... Thanks.

**Comment by skkuull** [comment]
We dont support those anymore.

**Comment by khabib227** [comment]
All other Call of Duty mods has the files available, why not with H1? Just H1 has issues with copy rights?
